AllCops:
  TargetRubyVersion: 2.6

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - apps/web/application.rb
    - spec/**/*.rb

Layout/LineLength:
  Description: 'Limit lines to 100 characters.'
  Enabled: true
  Max: 100
  AllowURI: true
  URISchemes:
  - http
  - https

Layout/ArgumentAlignment:
  StyleGuide: '#no-double-indent'
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/DotPosition:
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#consistent-multi-line-chains'
  EnforcedStyle: trailing

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation
