Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - apps/web/application.rb
    - spec/**/*.rb

Layout/LineLength:
  Description: 'Limit lines to 100 characters.'
  Enabled: true
  Max: 100
  AllowURI: true
  URISchemes:
  - http
  - https

Layout/ArgumentAlignment:
  Description: >-
                 Align the arguments of a method call if they span more
                 than one line.
  StyleGuide: '#no-double-indent'
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/DotPosition:
  Description: 'Checks the position of the dot in multi-line method calls.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#consistent-multi-line-chains'
  EnforcedStyle: trailing
